version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fraudshield-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: always
    # We name it 'backend' so the frontend Apache config can find it at http://backend:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fraudshield-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

networks:
  default:
    name: fraudshield-network
